name: 'Notion DB pages payload for slack'
description: 'Generate Notion DB pages query result payload for Slack notify'
author: 'litencatt'
inputs:
  header:
    default: ''
    description: 'A header contain to slack send message'
    required: false
  description:
    default: ''
    description: 'A description contain to slack send message'
    required: false
  # https://developers.notion.com/reference/post-database-query-filter
  filter:
    description: 'JSON filter payload to query to Notion database'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
